---

- hosts: all
  become: true
  tasks:
    - name: install apache
      yum:
        name: httpd
        state: latest
      when: ansible_distribution == "Amazon"
    - name: install php
      yum:
        name: php
        state: latest
      when: ansible_distribution == "Amazon"

